#!/bin/bash

# We don't currently have any precommit hooks so this one is a no-op.
# Some may still have it configured though so we just do nothing instead of deleting it.

# exit cleanly to let commit continue
exit 0
