ALTER TABLE raids ADD COLUMN IF NOT EXISTS `costume` SMALLINT UNSIGNED NULL DEFAULT 0 AFTER `gender`;

ALTER TABLE raid_bosses ADD COLUMN IF NOT EXISTS `scheduled` TINYINT(1) NULL DEFAULT NULL AFTER `raid_level`;
