ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `gymarea` TINYINT UNSIGNED NULL AFTER `auto_alarm`;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `privileges` TEXT NULL AFTER `gymarea`;

ALTER TABLE `photo_cache` ADD COLUMN IF NOT EXISTS `end_time` DATETIME NULL AFTER `ended`;
ALTER TABLE `photo_cache` ADD COLUMN IF NOT EXISTS `start_time` DATETIME NULL AFTER `ended`;

ALTER TABLE `pokemon` DROP COLUMN IF EXISTS `asset_suffix`;
